
# This file is automatically generated, you probably don't want to edit this

itemfitBase <- R6::R6Class(
    "itemfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
            super$initialize(
                package = 'easyRaschJamovi',
                name = 'itemfit',
                version = c(1, 0, 0),
                options = options,
                results = jmvcore::Group$new(
                    options = options,
                    name = "results",
                    items = list(
                        jmvcore::Table$new(
                            options = options,
                            name = "fitTable",
                            title = "Item Fit Statistics",
                            rows = "(vars)",
                            columns = list(
                                jmvcore::Column$new(
                                    name = "item",
                                    title = "Item",
                                    type = "text"
                                ),
                                jmvcore::Column$new(
                                    name = "infitmsq",
                                    title = "InfitMSQ",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "location",
                                    title = "Relative location",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "thresholds",
                                    title = "Thresholds",
                                    type = "text"
                                )
                            )
                        )
                    )
                ),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision
            )
        })
)
