
# This file is automatically generated, you probably don't want to edit this

rescorBase <- R6::R6Class(
    "rescorBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
            super$initialize(
                package = 'easyRaschJamovi',
                name = 'rescor',
                version = c(1, 0, 0),
                options = options,
                results = jmvcore::Group$new(
                    options = options,
                    name = "results",
                    items = list(
                        jmvcore::Html$new(
                            options = options,
                            name = "residcorr",
                            title = "Residual Correlation Matrix"
                        )
                    )
                ),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision
            )
        })
)
